mx_node_configs:
  - name: "node1"
    operations(a):
      - main_op_name: "valgen:range"
        condition_op_name: "condition:true"
        read_paths:
          boundary: "@(1,10)"
          is_integer: "@True"
          count: "@5"
        write_path: "$.target"
    conditions(a):
      true: "node2"
    operations(b):
      - main_op_name: "valgen:range"
        condition_op_name: "condition:true"
        read_paths:
          boundary: "@(3,6)"
          is_integer: "@True"
          count: "@1"
        write_path: "$.source"
    conditions(b):
      true: "node2"
  - name: "node2"
    operations(a):
      - main_op_name: "property:sample"
        condition_op_name: "condition:true"
        read_paths:
          property_name: "date_alias"
        write_path: "$.category"
    conditions(a):
      true: "node3"
    operations(b):
      - main_op_name: "judge:include"
        condition_op_name: "condition:identity"
        read_paths:
          source: "$.source"
          target: "$.target"
        write_path: "$.comparison"
  - name: "node3"
    operations(a):
      - main_op_name: "relative:date"
        condition_op_name: "condition:true"
        read_paths:
          reference_date: "2026-01-01"
          shift: "$.category"
        write_path: "$.result"
properties:
  - property_name: date_alias
    categories:
      - category_name: "+1D"
        weight: 1.0
        items:
          - item_name: "tomorrow"
            weight: 1.0
          - item_name: "next day"
            weight: 2.0
      - category_name: "-1D"
        weight: 2.0
        items:
          - item_name: "yesterday"
            weight: 2.0
          - item_name: "previous day"
            weight: 1.0